name: Build luci-app-smart-mini

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download SDK
        run: |
          wget https://downloads.openwrt.org/releases/23.05.4/targets/mediatek/filogic/openwrt-sdk-23.05.4-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64.tar.xz
          tar xf openwrt-sdk-23.05.4-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64.tar.xz

      - name: Copy plugin
        run: |
          cp -r luci-app-smart-mini ./openwrt-sdk-23.05.4-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/package/

      - name: Prepare
        run: |
          cd openwrt-sdk-23.05.4-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64
          ./scripts/feeds update -a || true
          ./scripts/feeds install -a || true
          make defconfig

      - name: Compile plugin
        run: |
          cd openwrt-sdk-23.05.4-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64
          make package/luci-app-smart-mini/compile V=s

      - name: Upload IPK
        uses: actions/upload-artifact@v4
        with:
          name: luci-app-smart-mini-ipk
          path: openwrt-sdk-23.05.4-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/bin/packages/**/luci/luci-app-smart-mini*.ipk
