name: Build luci-app-smart-mini

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # ✅ 修正这里：你写成 upload-artifact 了

    - name: Setup OpenWRT SDK
      run: |
        wget https://downloads.openwrt.org/releases/23.05.4/targets/aarch64/cortexa53/openwrt-sdk-23.05.4-aarch64-cortexa53_gcc-12.3.0_musl.Linux-x86_64.tar.xz
        tar -xf openwrt-sdk-23.05.4-aarch64-cortexa53_gcc-12.3.0_musl.Linux-x86_64.tar.xz

    - name: Copy plugin to SDK
      run: |
        cp -r luci-app-smart-mini ./openwrt-sdk-23.05.4-aarch64-cortexa53_gcc-12.3.0_musl.Linux-x86_64/package/

    - name: Prepare SDK
      run: |
        cd openwrt-sdk-23.05.4-aarch64-cortexa53_gcc-12.3.0_musl.Linux-x86_64
        ./scripts/feeds update -a || true
        ./scripts/feeds install -a || true
        make defconfig

    - name: Compile luci-app-smart-mini
      run: |
        cd openwrt-sdk-23.05.4-aarch64-cortexa53_gcc-12.3.0_musl.Linux-x86_64
        make package/luci-app-smart-mini/compile V=s

    - name: Upload all IPKs
      uses: actions/upload-artifact@v4
      with:
        name: luci-app-smart-mini-ipk
        path: openwrt-sdk-23.05.4-aarch64-cortexa53_gcc-12.3.0_musl.Linux-x86_64/bin/packages/**/luci/luci-app-smart-mini*.ipk
